apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-deployment
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  project: default
  source:
    repoURL: 'https://github.com/simbask/argocdTut'
    path: dev
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated: 
      selfHeal: true
      prune: true